#!/bin/sh

regex='(?:https?|ftp):\/\/[a-zA-Z0-9]+(?:(?:\.|\-+)[a-zA-Z0-9]+)*(?::[0-9]+)?(?:(?:\/|#)[a-zA-Z0-9.$&%?#=_~\-]*)*[^ .,!?;\t>"():]'
font='FantasqueSansMono Nerd Font Mono:pixelsize=14:antialias=true:autohint=true'
selbg='#d8a657'
normalbg='#32302f'
url=$(grep -aPo "$regex" | dmenu -fn "$font" -nb "$normalbg" -sb "$selbg" -i -h 24 -l 7 -p "open url:" -w "$WINDOWID") || exit
echo "$url" | while IFS= read -r line ; do
    $BROWSER "$line"
done

